#pragma once

#define GRABBER_LEFT_MOTOR 4
#define GRABBER_RIGHT_MOTOR 3
#define GRABBER_GARRY_MOTOR 2

#define GRABBER_UP_SWITCH 2
#define GRABBER_DOWN_SWITCH 0
#define GRABBER_IN_SWITCH 1
#define GRABBER_SWITCH_POSITION 9

#define SHOOTER_LEFT_MOTOR 1
#define SHOOTER_RIGHT_MOTOR 0

#define CHASSIS_RIGHT_FRONT 6
#define CHASSIS_RIGHT_REAR 5
#define CHASSIS_LEFT_FRONT 8
#define CHASSIS_LEFT_REAR 7

#define DRIVER_JOYSTICK 0
#define OPERATOR_JOYSTICK 1

#define JOYSTICK_BUTTON_A 1
#define JOYSTICK_BUTTON_B 2
#define JOYSTICK_BUTTON_X 3
#define JOYSTICK_BUTTON_Y 4
#define JOYSTICK_BUTTON_L_BUMPER 5
#define JOYSTICK_BUTTON_R_BUMPER 6
#define JOYSTICK_BUTTON_START 7
#define JOYSTICK_BUTTON_SELECT 8
#define JOYSTICK_BUTTON_L_STICK 9
#define JOYSTICK_BUTTON_R_STICK 10
